seed: 42

data:
  data_dir: data
  batch_size: 256
  num_workers: 4
  image_size: 96
  pin_memory: true

model:
  lr: 0.001
  weight_decay: 0.0001
  temperature: 0.2
  proj_hidden_dim: 2048
  proj_out_dim: 128
  use_bn_in_head: true

trainer:
  max_epochs: 10
  precision: 16-mixed
  accumulate_grad_batches: 1
  log_every_n_steps: 20
